---
name: renovate
on:
  schedule:
    - cron: '17 3 * * 1'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  renovate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@5402b206248e5a8c8427a15102702eb9c1793efc # v46.2.4
        with:
          configurationFile: renovate.json5
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          RENOVATE_ALLOWED_COMMANDS: '["^scripts/update-yq-checksum\\.sh$"]'
